# permissions for end users to view l2cruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: l2crun-viewer-role
rules:
- apiGroups:
  - l2c.my.domain
  resources:
  - l2cruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - l2c.my.domain
  resources:
  - l2cruns/status
  verbs:
  - get
